### ISSUE TITLE
Beschreibung im CM

### ISSUE THREAD

**Issue by zonky2** [eS-IT/datacollections#3]
Die Beschreibung "Es handelt sich um eine Erweiterung für das Open Source CMS Contao" ist eher selbstverständlich... eine Info was die macht, dafür hilfreicher ;-)

**Comment by eS-IT** [comment]
Steht im zweiten Satz. Da ich nicht nur Erweiterungen für Contao schreiben, ist dies in der README ein wichtiger Hinweis.

**Comment by zonky2** [comment]
es gibt keinen zweiten Satz - das meinte ich damit...

![image](https://github.com/user-attachments/assets/561ed814-81df-4e2d-9ecf-cf9b0f11df30)

Mit "CM" meinte ich den Contao-Manager bzw. die Extension-Seite.

**Comment by eS-IT** [comment]
Ich nutze den Manager nicht, deshalb hat er keine hohe Priorität. Ich habe aber im Dev-Branch die Beschreibung aus der Readme in die composer.json kopiert.
